site_name: N5 CS

theme:
    name: readthedocs

navigation_depth: 4

nav:
    - Home: index.md
    - SDD:
        - Software: sdd/N5-CS-SDD.md
        - Data: sdd/N5-CS-SDD-Data.md
        - Assignment: Nsdd/5-CS-SDD-Assignment.md
        - Arithmetic: sdd/N5-CS-SDD-Arithmetic.md
        - Concatenation: sdd/N5-CS-SDD-Concatenation.md
        - User input: sdd/N5-CS-SDD-Input.md
        - Comparison operators: sdd/N5-CS-SDD-Comparisons.md
        - Selection - Simple: sdd/N5-CS-SDD-Selection-Simple.md
        - Logical operators: sdd/N5-CS-SDD-Logic.md
        - Selection - Complex: sdd/N5-CS-SDD-Selection-Complex.md
        - Loops: sdd/N5-CS-SDD-Loops.md
        - Predefined functions: sdd/N5-CS-SDD-Functions.md
        - Standard algorithms: sdd/N5-CS-SDD-Standard-Algorithms.md
    - DDD:
        - Databases: ddd/N5-CS-DDD.md
        - Display data results: ddd/N5-CS-DDD-Select.md
        - Filter results: ddd/N5-CS-DDD-Where.md
        - Sort results: ddd/N5-CS-DDD-Order.md
        - Joining tables: ddd/N5-CS-DDD-Equi-join.md
        - Add data: ddd/N5-CS-DDD-Insert.md
        - Modify data: ddd/N5-CS-DDD-Update.md
        - Remove data: ddd/N5-CS-DDD-Delete.md
        - Create table: ddd/N5-CS-DDD-Create-Table.md
        - Modify table: ddd/N5-CS-DDD-Modify-Table.md
        - Examples: ddd/N5-CS-DDD-Examples.md
    - WDD:
        - Web: wdd/N5-CS-WDD.md